---
title: "Presentation graphs"
author: "Gage Clawson"
date: "2/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here())

pepela <- read_csv(file.path(here(), "hypo_village_data/Pepela/pepela_all_predictions_FINAL.csv"))

psc <- read_csv(file.path(here(), "hypo_village_data/PuertoSanCarlos/psc_all_predictions_FINAL.csv"))
```

Pepela Graphs

```{r}
#Non anonymous, publicly available

pepela %>%
  filter(opt_in_out == "Opt In", package %in% c(8,11), regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Non-anonymous, Public access", title = "Pepela") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#Non anonymous, government
pepela %>%
  filter(opt_in_out == "Opt In", info == 1, own == 3, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Non-anonymous, Government", title = "Pepela") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#Non anonymous, industry
pepela %>%
  filter(opt_in_out == "Opt In", info == 1, own == 2, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Non-anonymous, Industry", title = "Pepela") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#Non anonymous, fisher
pepela %>%
  filter(opt_in_out == "Opt In", info == 1, own == 1, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Non-anonymous, Fisher Community", title = "Pepela") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#anonymous, publicly available

pepela %>%
  filter(opt_in_out == "Opt In", info == 0, own == 4, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Anonymous, Public access", title = "Pepela") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#anonymous, government
pepela %>%
  filter(opt_in_out == "Opt In", info == 0, own == 3, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Anonymous, Government", title = "Pepela") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#anonymous, industry
pepela %>%
  filter(opt_in_out == "Opt In", info == 0, own == 2, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Anonymous, Industry", title = "Pepela") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#Anonymous, fisher
pepela %>%
  filter(opt_in_out == "Opt In", info == 1, own == 1, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Anonymous, Fisher Community", title = "Pepela") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

```

Puerto San Carlos

```{r}
#Non anonymous, publicly available

psc %>%
  filter(opt_in_out == "Opt In", package %in% c(8,11), info == 1, own ==4, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Non-anonymous, Public access", title = "Puerto San Carlos") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4, 5, 6)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#Non anonymous, government
psc %>%
  filter(opt_in_out == "Opt In", info == 1, own == 3, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Non-anonymous, Government", title = "Puerto San Carlos") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4, 5, 6)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#Non anonymous, industry
psc %>%
  filter(opt_in_out == "Opt In", info == 1, own == 2, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Non-anonymous, Industry", title = "Puerto San Carlos") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4, 5, 6)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#Non anonymous, fisher
psc %>%
  filter(opt_in_out == "Opt In", info == 1, own == 1, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Non-anonymous, Fisher Community", title = "Puerto San Carlos") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4, 5, 6)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#anonymous, publicly available

psc %>%
  filter(opt_in_out == "Opt In", info == 0, own == 4, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Anonymous, Public access", title = "Puerto San Carlos") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4, 5, 6)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#anonymous, government
psc %>%
  filter(opt_in_out == "Opt In", info == 0, own == 3, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Anonymous, Government", title = "Puerto San Carlos") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4, 5, 6)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#anonymous, industry
psc %>%
  filter(opt_in_out == "Opt In", info == 0, own == 2, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Anonymous, Industry", title = "Puerto San Carlos") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4, 5, 6)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))

#Anonymous, fisher
psc %>%
  filter(opt_in_out == "Opt In", info == 1, own == 1, regression_type == "interval") %>%
  ggplot(aes(x = y, y = perc, color = factor(sos))) + 
    geom_line() +
    theme_bw() +
    labs(caption = "Anonymous, Fisher Community", title = "Puerto San Carlos") +
    labs(x = "Cost to Fisher ($ per month)", y = "Proportion of Population to Opt In") +
    #geom_vline(xintercept = c(-1.88, -0.61), linetype = "dotted", color = "darkgreen") +
     #geom_vline(xintercept = c(3.15, 4.41), linetype = "dotted", color = "red") +
        scale_x_continuous(breaks = c(-3,-2, -1, 0, 1, 2,3 ,4, 5, 6)) +
    #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_color_manual(values = c("goldenrod1", "lightseagreen"), name = "SOS Functionality", labels = c("No", "Yes"))  +
    scale_y_continuous(breaks = seq(0,1, 0.2))


```



